### ISSUE TITLE
Does not highlight django tags properly

### ISSUE THREAD

**Issue by GoogleCodeExporter** [tobias47n9e/gedit-django-template-language#1]
What steps will reproduce the problem?
1. put dtl.lang in gtksourceview directory
2. start gedit and enter in django template syntax used here:
   http://docs.djangoproject.com/en/dev/topics/templates/
3. endblock is not highlighted, yet 'section' word is

What is the expected output? What do you see instead?

:: endblock should be highlighted, should section be highlighted?

What version of the product are you using? On what operating system?

:: ubuntu intrepid ibex

Original issue reported on code.google.com by `lee.a.co...@gmail.com` on 13 Dec 2008 at 2:15

**Comment by tobias47n9e** [comment]
This bug seems to have been fixed already.
