### ISSUE TITLE
comment and endcomment not supported ?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [tobias47n9e/gedit-django-template-language#2]
What steps will reproduce the problem?
1. use a block comment:

``` django
{% comment %} my comments {% endcomment %}
```

What is the expected output? What do you see instead?

``` django
{% comment %} my comments {% endcomment %}
```

should use the comment's color but 
it's displayed as normal block with text inside.

Original issue reported on code.google.com by `d.cor...@webu.fr` on 1 Feb 2014 at 4:02

**Comment by tobias47n9e** [comment]
More information about these comment:

https://docs.djangoproject.com/en/1.8/ref/templates/builtins/#std:templatetag-comment

**Comment by tobias47n9e** [comment]
This should  be fixed now.
